import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relativ container min-h-full bg-teal-400">test</div>
    </>
  )
}

export default Home
